### ISSUE TITLE
cmake and VS2017 msvc 15.9.24 fail to build[BUG]

### ISSUE THREAD

**Issue by jdmairs** [bluescarni/heyoka#156]
**Describe the bug**
VS2017 15.9.24 msvc fails to build heyoka source during build phase due to numerous errors such as
'warning treated as error',
'noexcept is not a special member function that can be defaulted'

**To Reproduce**
1. cmake build and install all pre-reqs llvm 10, fmt 7.1.3, spdlog 1.8.5, boost 1.73
2. cmake -G "Visual Studio 15 2017 Win64" ..
3. cmake --build .
4. numerous errors

**Expected behavior**
github homepage says msvc is supported...perhaps only VS2019?

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Windows 10
 - Installation method: [source]
 - Version: [0.10]

**Additional context**

**Comment by bluescarni** [comment]
Indeed we continuously test only MSVC 2019:

https://github.com/bluescarni/heyoka/runs/2963186716?check_suite_focus=true#step:5:337

We also test build using MSVC 2017's standard library in conjunction with the clang compiler:

https://ci.appveyor.com/project/bluescarni/heyoka/builds/39835569#L325

I think at one point I made an attempt to build with MSVC 2017, but the compiler had too many issues with various C++17 constucts we extensively use in heyoka.

Probably, as you point out, we should be more specific about the tested MSVC versions in the docs.

**Comment by jdmairs** [comment]
Would the following work...
Rebuild llvm v10 to include clang.
Use clang instead of msvc in my CMake toolchain.
Compile/install heyoka via clang.
In my program include/link to heyoka using msvc 2017.

**Comment by bluescarni** [comment]
@jdmairs you don't really need to build clang yourself, you can just install a binary package for Windows. The version of clang you use to compile heyoka can be different from the version of the LLVM libraries you link into heyoka - the two are completely decoupled.

Compiling/installing heyoka with clang and then compiling your code with msvc 2017 **may** work, but there could be issues related to the fact that some heyoka functions are templates and thus you will have to compile them with MSVC 2017 when you are using heyoka as a dependency in your code. Best would be to just always use clang - it is binary compatible with MSVC, but I understand that might be a bit of an issue in practice.

**Comment by jdmairs** [comment]
I guess my other option would be to simply use boost::odeint.  It doesn't
look like it's being maintained anymore.

**Comment by bluescarni** [comment]
@jdmairs my advice for heyoka would be to just use the conda package. With conda you can install heyoka and clang, and you don't need to worry about dependencies, MSVC incompatibilities, etc.

**Comment by jdmairs** [comment]
You've been a great help...thank you.
Unfortunately i'm on an offline network so I have to build everything by
source.
thank goodness for cmake

**Comment by sixteenornumber** [comment]
My organization also requires building from source so I'm in the same boat.  Is there any plan to fix this?

**Comment by bluescarni** [comment]
@sixteenornumber building from source should not be a problem if you are using either

* MSVC 2019, or
* MSVC 2017 + ``clang-cl``.

The default compiler ``cl.exe`` from MSVC 2017 does not support adequately certain C++17 constructs used in the heyoka source code, hence the necessity to use ``clang-cl`` instead (which will however produce code which is binary compatible with ``cl.exe``).

Does your organization mandate the use of MSVC 2017?

**Comment by bluescarni** [comment]
I will close this report as compilation with MSVC 2019 works and I don't have the bandwidth to make an attempt to workaround MSVC 2017 deficiencies.
