### ISSUE TITLE
Partial derivative with respect to time not implemented in .diff utility [BUG]

### ISSUE THREAD

**Issue by guescrib** [bluescarni/heyoka#159]
**Describe the bug**
Tried to compute the variational equations of a non-autonomous system - of the form dx/dt = f(x,t) - but the following error shows up:
_NotImplementedError: The derivative is not implemented for the function 'time'_

**To Reproduce**
Write a non-autonomous system like:

x, v = hy.make_vars("x", "v")
state = [x,v]
sys = [x, v, hy.cos(hy.time) - .1 * v - hy.sin(x))]

And then compute the partial derivatives of the system with respect to the state variables

for i in range(sys)
    for j in range(state)
        varsys[i][j] = hk.diff(sys[i],state[j])

**Expected behavior**
Partial derivative of time with respect to any state variable should be zero as far as I understand... (Given we adopt a Newtonian approach)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Installation method: conda
 - Version: 0.10

**Comment by bluescarni** [comment]
Hi @guescrib,

thanks for the report, this should be a fairly easy one to fix. I'll open a PR and try to publish a new release today.

**Comment by bluescarni** [comment]
PR up at #160.

**Comment by bluescarni** [comment]
@guescrib the new heyoka/heyoka.py versions (0.11.0) should be available shortly on the conda-forge channel. I'll close this report for the time being, feel free to re-open if you still experience issues.

**Comment by guescrib** [comment]
Thank you @bluescarni for the quick response and fix!
