### ISSUE TITLE
Issue on page /index.html

### ISSUE THREAD

**Issue by jdmairs** [bluescarni/heyoka#177]
I just built heyoka from source and the pendulum example.  I ran it and saw the following screen output:
x(10) = 0.0487397
y(10) = 0.0429423

does this look accurate and if so perhaps adding the sample output to your main page would help others

thanks!

**Comment by jdmairs** [comment]
Also I cannot explain this interesting behavior with pendulum...
The numbers print out as shown above but the program does not exit immediately.  It sits for ~45 seconds before exiting completely.  If I use processExplorer (Windows 10) it shows 2 processes named pendulum.exe and one of them is SUSPENDED...they they both exit at same time.

**Comment by bluescarni** [comment]
@jdmairs those values look correct, I'll make sure to add them to the docs - thanks for the suggestion.

Regarding your second point, could you explain in more detail what you did? The test suite, when run in the continuous integration setup on Windows, does not show the behaviour you mention:

https://ci.appveyor.com/project/bluescarni/heyoka/builds/40131424

(if you scroll towards the end of the log, you will see that there are many tests that run just for a handful of seconds)

Perhaps you could try to compile and run the test suite to see if the same behaviour shows up there?

**Comment by bluescarni** [comment]
Closing this report in the meantime. Please let me know if you run into further issues on Windows @jdmairs
