### ISSUE TITLE
[FEATURE] Consider submitting heyoka package to spack

### ISSUE THREAD

**Issue by agseaton** [bluescarni/heyoka#374]
First off, thank you for developing this excellent library!

heyoka has some pretty hefty dependencies (LLVM!), so it would be nice to have more options for obtaining binaries. For example, on one of the clusters I use I don't have anaconda available to install the prebuilt binaries, and the LLVM version available is too old. I'd need to compile a more recent version of LLVM which is not exactly trivial...

However, on many HPC systems it is now common to use [spack](https://spack.io/) to simplify this process, since it automates obtaining and compiling dependencies.

heyoka doesn't yet have an entry in the spack package database, and I realise this would be extra work to maintain, but if you would consider submitting a package recipe to spack it might simplify the installation process for users.

Spack has great documentation on putting together a package recipe (see [here](https://spack.readthedocs.io/en/latest/packaging_guide.html)).

As a starting point, I was able to put together a package recipe ([here](https://pastebin.com/BR5nQTBd)) using the heyoka build documentation. This seems to work well; installing heyoka (and all required dependencies) becomes as simple as running `spack install heyoka`.

**Comment by bluescarni** [comment]
@agseaton thanks for the kind words.

It would certainly be great to have heyoka available on spack, but my bandwidth for packaging tasks at the moment is fairly limited as I am already maintaining the conda packages for both heyoka and heyoka.py, and the manylinux wheels for heyoka.py.

The spack recipe looks pretty short and sweet, but what about the other steps of the process? I.e., is there a centralised repository with pre-built binary packages or does one always build from source? Is there a (semi-)automated process for updating the recipe when new versions of heyoka (or its dependencies) are released?

Also, would you consider helping out with maintaining the spack recipe?

**Comment by agseaton** [comment]
I think the idea is that spack will build from source by default, but they do also maintain binaries compiled for various standard platforms (e.g. Ubuntu x86-64) which users can opt to use to save time. I don't think we would need to provide those, they are generated from the recipe automatically.

As a brief aside, my understanding is that spack was initially aimed at HPC admins who want very specific control of the software stack (e.g. which compiler is used, which MPI implementation, compiling for particular hardware, etc. etc.). So that explains the approach they have taken, but it also works well for a regular user since you aren't required to specify all of those details and can just run `spack install <somepackage>`.

The recipe will need to be updated when new versions are released and I think that unfortunately has to be done manually.

I'd certainly be happy to help out with maintaining a spack recipe if you don't mind me submitting it to spack. I can also look into submitting one for heyoka.py.

**Comment by bluescarni** [comment]
> I'd certainly be happy to help out with maintaining a spack recipe if you don't mind me submitting it to spack. I can also look into submitting one for heyoka.py.

Cheers, that's great to hear! Please feel free to go ahead.

We can keep this issue open for communicating, please don't hesitate to ping me in case you need any assistance/clarification for compiling heyoka/heyoka.py.

**Comment by agseaton** [comment]
Sure, I'll try to flesh out what I have already and get it submitted.

One thing that would be helpful would be a more complete idea of which versions of the dependencies are required.

The heyoka documentation lists those for a few of the dependencies, but do you have an idea of what the requirements are for spdlog, TBB, SLEEF, and xtensor?

**Comment by bluescarni** [comment]
@agseaton xtensor is used only in the unit tests, so I do not think it is necessary to add it as a dependency in the spack recipe?

TBB has a stable API, so basically any version released in the last couple of years should work.

spdlog also has a stable API, but it has a bit of a finicky relation with fmt. Basically one needs to:

- ensure that spdlog works well with the selected fmt version,
- ensure that spdlog is **not** built  against its own internal bundled copy of fmt , but rather against an external installation of fmt.

Regarding SLEEF, I have only ever tested against the latest version (3.5.1).

**Comment by bluescarni** [comment]
Regarding spdlog, usually the compatibility with fmt is detailed in the release notes, e.g., see here:

https://github.com/gabime/spdlog/releases/tag/v1.12.0

**Comment by agseaton** [comment]
Okay great.

spack allows adding optional dependencies, so I can specify that heyoka depends on xtensor only when the unit tests are enabled.

Regarding the spdlog/fmt issue, I have ensured that spdlog is built with the external fmt library so that should not be an issue. Also it looks like the spdlog spack recipe already has some constraints on the fmt version so I don't think we need to do anything special there.

**Comment by agseaton** [comment]
Quick update on this -- my package recipes for heyoka and mppp were approved and [merged into spack](https://github.com/spack/spack/pull/41839) today. They will need to be updated whenever there's a new release of either package.

You can now install heyoka (and its dependencies) via spack by running `spack install heyoka`.

It might be nice to have this installation route mentioned in the heyoka documentation. If this sounds good to you I'd be happy to write some basic instructions.

**Comment by bluescarni** [comment]
Hi @agseaton thanks a lot for pushing this through and apologies for not having had the time to follow this more closely.

It would be great it you could add a short paragraph about installation via spack to the installation guide in a pull request. The file to modify would be ``doc/install.rst``.

**Comment by agseaton** [comment]
Hey sorry for dropping the ball on this. And yes, that looks fine to me.
