### ISSUE TITLE
serialization fails(MSVC)

### ISSUE THREAD

**Issue by 7ofNine** [bluescarni/heyoka#431]
Hello Franceso,
I finally managed after along time to compile heyoka but in running the tests I am running into failures with the Boost serialization.
I am using, as always, MSVC (Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.10.2) and 8/140 tests fail.
...
1>	  7 - func (Failed)
1>	 11 - taylor_adaptive (Failed)
1>	 13 - taylor_t_event (Failed)
1>	 14 - taylor_nt_event (Failed)
1>	 15 - taylor_adaptive_batch (Failed)
1>	 98 - batch_event_detection (Failed)
1>	115 - step_callback (Failed)
1>	117 - angle_reducer (Failed)
...
 So far I have looked at func and angle_reducer and they both show the same symptoms. Func actually for two different tests
...
D:\Dev\Astronomy\heyoka\test\angle_reducer.cpp(105): FAILED:
due to unexpected exception with message:
  unregistered class - derived class not registered or exported
...

The actual failure happens when attempting to write to the archive with the "<<" operator.

The heyoka version is 5.0.0 and Boost is 1.85.0.
The usual question is it me in my setup or is there some serialization registration/export missing that shows it ugly head only when using MSVC?

Hartmuth

**Comment by bluescarni** [comment]
Hi @7ofNine , are you building heyoka as a static or dynamic library?

Also, is there any chance you have multiple Boost versions being loaded/linked in when you run these tests (I vaguely remember MSVC having some special pragmas - used by Boost - for autoloading/autolinking dynamics libraries)?

**Comment by 7ofNine** [comment]
Hi Franceso,
The above result came from a build with heyoka as dll and mppp and sleef. Removing mppp and sleef didn't change the result.
The boost library is 1.85.0 and as far as I could find none of the other libraries actually uses boost. And to make sure I removed my previous boost installation (1.83.0) but no change. A copy of the boost dll for serialization is in the test/Release directory and no path to any boost installation is set. The only way to load it is from this directory.  

I also recompiled heyoka using a static library and interestingly most of the above failures (except for two) disappear but another set of failures show up. In total I get 11 failures and I think only two of them are the serialization errors. The other ones are all about not finding a symbol. They are all similar to
...

cfunc vsop2013
-------------------------------------------------------------------------------
D:\Dev\Astronomy\heyoka\test\expression.cpp(1450)
...............................................................................

D:\Dev\Astronomy\heyoka\test\expression.cpp(1450): FAILED:
due to unexpected exception with message:
  Could not find the symbol 'heyoka.obj_trigger' in the compiled module

===============================================================================
test cases:    36 |    35 passed | 1 failed
assertions: 11041 | 11040 passed | 1 failed
...

The total list of failures is:
...
 static heyoka.lib
1>The following tests FAILED:
1>	  3 - expression (Failed)
1>	 13 - taylor_t_event (Failed)
1>	 42 - taylor_kepE (Failed)
1>	 43 - taylor_kepF (Failed)
1>	 80 - kepE (Failed)
1>	 81 - kepDE (Failed)
1>	 82 - kepF (Failed)
1>	 92 - llvm_helpers (Failed)
1>	 94 - vsop2013 (Failed)
1>	101 - parallel_mode (Failed)
1>	115 - step_callback (Failed)
...
This is a failure I don't see anywhere when using a dll but I remember from my first trials for heyoka some possibly 2 years ago that I saw the same error popping up. Meanwhile everything has been recompiled with different versions and llvm has been upgraded a couple of times.
It remains interesting.  For the above case who is not finding a symbol? llvm?

Hartmuth

**Comment by bluescarni** [comment]
Hi Hartmuth,

regarding the static build of the heyoka library, that is unused and untested, and I am not even sure it can work at all due to the way external symbols are looked up from the JIT-compiled code. I was asking just  to make sure we were not seeing weird behaviour from an untested build setup :)

The serialisation issue definitely seems to be pointing in the direction of either some Boost weirdness or some peculiarity in your setup. Windows building with MSVC is regularly tested in the CI, using the conda packages for Boost (and for the other heyoka dependencies as well):

https://github.com/bluescarni/heyoka/actions/runs/9529389697/job/26268091097#step:5:209

If you can live without serialisation support (which is most likely, as that is a quite niche feature), you could also ignore the test failures altogether.

**Comment by 7ofNine** [comment]
Hi Francesco,
I removed the fancy libraries mppp and sleef and tried the static version "for fun" in order to see what is different. As such there seems to be an issue with using JIT in some cases. I collected the different cases. In any case it fails in the compile step after registering some objects. The easiest to follow up might be the llvm_helper test using the "llvm_add_inv_kep_E_wrapper" most of the other cases are happening with "taylor_adaptive", "taylor_adaptive_batch" and "add_cfunc". Ignoring those for the time being the interesting fact as is that only two of the serialization cases remain when using the static library vs. eight in the dynamic case, while in the dynamic case none of the JIT failures show up. 
I am always ready for an error somewhere in my own setup one of them is boost. I typically don't do anything with it. I compile it as it comes with the addition of the python libraries. And on the side my boost setup works fine for the serialization tests with good old piranha.
I will flip back to the dynamic version and continue from there. For the time I can live without the serialization. It is not very likely that I am going to use it. I just don't like bugs and even chase warnings, bad experience in a former professional life.

Unrelated to the above problem. There are a bunch of warnings popping up. One category is the usual type incompatibility with possible loss of information the other type is some deprecation warnings about unchecked iterators.

**Comment by bluescarni** [comment]
> Unrelated to the above problem. There are a bunch of warnings popping up. One category is the usual type incompatibility with possible loss of information the other type is some deprecation warnings about unchecked iterators.

Mmh.. are you by chance mixing up Release/Debug builds of heyoka, boost and/or other deps? I am aware of the "possible loss of information" warnings but I do not see the unchecked iterator warnings in my Windows builds (which are always in Release mode as all the conda packages I am using for dependency management are also all built in Release mode).

**Comment by 7ofNine** [comment]
I typically build in release. Debug is only done when I really run into trouble and I swear everytime of having to rebuild and reconfigure all kinds of other libraries. 
What could be a factor is that I am using the latest preview version of VS which possibly ahead of its time.

I also have now rebuild heyoka and all the tests using the boost version (1.84.0) that comes with the conda install following the test environment you use and magically no serialization errors pop up. Hmm. So far I have no idea what the differences are.
For the "unchecked iterator" I currently have it shut-up via pre-processor directive but I'll turn it on again an do builds using the conda installation instead of my local one and have a look if it still shows up. Another check I am going to do is building the static version again but use the conda version of llvm not my local one. 

An unrelated observation is that the link step for the msvc build uses /INCREMENTAL:YES which is quite resource hungry in the range of several GB of *.ilk files. I explicitly turned it off for the test targets which supposedly also makes the link faster. It looks like it is more of an advantage for debug builds and repeated builds when developing. It also is supposed to create bigger and slower executables as well as disallowing some runtime optimizations like link code generations. I don't have benchmarks for that.  Why I am mentioning it: It brought my hard drive to edge of a nervous breakdown.

I think the serialization issue is resolved even if I don't understand how this is the case, yet. And I close the issue
For the warnings I'll have look again and let you know If I see something. E.g. I haven't checked if the deprecation warning is dependent on a compiler version etc.

Hartmuth
